strategy: funding_arbitrage
created_at: '2025-10-21T20:00:21.285327'
version: '1.0'
config:
  scan_exchanges:
  - aster
  - lighter
  - paradex
  mandatory_exchange: lighter
  target_margin: !!float '40'
  max_positions: 1
  max_total_exposure_usd: !!float '2000'
  min_profit_rate: 0.0001283105022831050228310502283
  risk_strategy: combined
  profit_erosion_threshold: 0.4
  min_hold_hours: 1
  max_position_age_hours: 12
  max_new_positions_per_cycle: 1
  limit_order_offset_pct: 0.0002
  check_interval_seconds: 60
  dry_run: false
  max_oi_usd: !!float '5500000'
  min_volume_24h: !!float '350000'
  min_oi_usd: !!float '100000'
