strategy: funding_arbitrage
created_at: '2025-10-21T20:00:21.285327'
version: '1.0'
config:
  scan_exchanges:
  - aster
  - lighter
  mandatory_exchange: lighter
  target_exposure: !!float '120'
  max_positions: 1
  max_total_exposure_usd: !!float '200'
  min_profit_rate: 0.0002283105022831050228310502283
  risk_strategy: combined
  profit_erosion_threshold: 0.4
  min_hold_hours: 1
  max_position_age_hours: 168
  max_new_positions_per_cycle: 1
  limit_order_offset_pct: 0.0002
  check_interval_seconds: 60
  dry_run: false
  max_oi_usd: !!float '1500000'
