strategy: funding_arbitrage
created_at: '2025-10-09T17:05:25.722902'
version: '1.0'
config:
  primary_exchange: lighter
  scan_exchanges:
  - edgex
  - backpack
  - aster
  - lighter
  - grvt
  target_exposure: !!float '100'
  max_positions: 2
  max_total_exposure_usd: !!float '500'
  min_profit_rate: 0.001
  max_oi_usd: !!float '10000000'
  risk_strategy: combined
  profit_erosion_threshold: 0.3
  max_position_age_hours: 24
  max_new_positions_per_cycle: 1
  check_interval_seconds: 60
  dry_run: true
