strategy: funding_arbitrage
created_at: '2025-10-21T18:29:58.783038'
version: '1.0'
config:
  primary_exchange: null
  scan_exchanges:
  - backpack
  - lighter
  - grvt
  target_exposure: !!float '80'
  max_positions: 1
  max_total_exposure_usd: !!float '200'
  min_profit_rate: 0.0001
  max_oi_usd: !!float '10000000'
  risk_strategy: combined
  profit_erosion_threshold: 0.5
  max_position_age_hours: 14
  max_new_positions_per_cycle: 1
  limit_order_offset_pct: 0.0002
  check_interval_seconds: 60
  dry_run: false
