strategy: funding_arbitrage
created_at: '2025-10-09T18:45:38.838384'
version: '1.0'
config:
  primary_exchange: lighter
  scan_exchanges:
  - backpack
  - aster
  - lighter
  - grvt
  target_exposure: !!float '10'
  max_positions: 1
  max_total_exposure_usd: !!float '100'
  min_profit_rate: 0.0001
  max_oi_usd: !!float '10000000'
  risk_strategy: combined
  profit_erosion_threshold: 0.5
  max_position_age_hours: 24
  max_new_positions_per_cycle: 2
  check_interval_seconds: 60
  dry_run: false
